[package]
name = "rir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.9.0"
clap = {version = "3.2.16", features = ["derive"]}
bincode = "1.3.3"
serde = {version = "1.0", features = ["derive"]}
